### ISSUE TITLE
Tests fail on Ubuntu 15.04 with system libcrypto++

### ISSUE THREAD

**Issue by ckorn** [ola-ct/Qt-SESAM#55]
Just trying to create a Debian package for my Ubuntu software site getdeb.net.
Do not use the crypto lib in the 3rdparty directory but the lib from the repositories.

However, the tests fail:

```
make[2]: Entering directory '/home/korn/packages/sesam/tmp2/tmp2/qt-sesam-2.0.5/UnitTests'
QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}  ./Qt-SESAM-UnitTests 
********* Start testing of TestSESAM *********
Config: Using QtTest library 5.4.1, Qt 5.4.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.9.2)
PASS   : TestSESAM::initTestCase()
PASS   : TestSESAM::qt_hmac_1()
PASS   : TestSESAM::qt_hmac_2()
PASS   : TestSESAM::qt_hmac_empty_message()
PASS   : TestSESAM::qt_hmac_empty_key()
PASS   : TestSESAM::base64()
PASS   : TestSESAM::pbkdf2()
PASS   : TestSESAM::pbkdf2_empty_salt()
PASS   : TestSESAM::pbkdf2_empty_message()
PASS   : TestSESAM::pbkdf2_long_message()
PASS   : TestSESAM::pbkdf2_sha384()
PASS   : TestSESAM::pbkdf2_sha256()
PASS   : TestSESAM::pwdgen_simple_1()
PASS   : TestSESAM::pwdgen_simple_password_2()
PASS   : TestSESAM::pwdgen_pin()
PASS   : TestSESAM::pwdgen_binary_salt_and_password()
Qt-SESAM-UnitTests: /usr/include/crypto++/secblock.h:151: void CryptoPP::NullAllocator<T>::deallocate(void*, CryptoPP::NullAllocator<T>::size_type) [with T = unsigned int; CryptoPP::NullAllocator<T>::size_type = long unsigned int]: Assertion `false' failed.
Aborted (core dumped)
Makefile:291: recipe for target 'check' failed
make[2]: *** [check] Error 134
make[2]: Leaving directory '/home/korn/packages/sesam/tmp2/tmp2/qt-sesam-2.0.5/UnitTests'
```

Will skip the tests until it's fixed.

And thanks for this great piece of software.
Just read in c't about it and love it ;)

**Comment by ckorn** [comment]
Ok, not only the tests are affected but also the app crashes on saving.
This is the stacktrace:

```
$ gdb ./Qt-SESAM 
GNU gdb (Ubuntu 7.9-1ubuntu1) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Qt-SESAM...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/korn/packages/sesam/tmp2/tmp2/qt-sesam-2.0.5/Qt-SESAM/Qt-SESAM 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Qt-SESAM: /usr/include/crypto++/secblock.h:151: void CryptoPP::NullAllocator<T>::deallocate(void*, CryptoPP::NullAllocator<T>::size_type) [with T = unsigned int; CryptoPP::NullAllocator<T>::size_type = long unsigned int]: Assertion `false' failed.
[New Thread 0x7fffd87f8700 (LWP 26338)]
[New Thread 0x7fffe45d4700 (LWP 26279)]
[New Thread 0x7fffeca33700 (LWP 26276)]

Program received signal SIGABRT, Aborted.
0x00007ffff5a9b267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5a9b267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff5a9ceca in __GI_abort () at abort.c:89
#2  0x00007ffff5a9403d in __assert_fail_base (
    fmt=0x7ffff5bf6028 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x489410 "false", 
    file=file@entry=0x489498 "/usr/include/crypto++/secblock.h", 
    line=line@entry=151, 
    function=function@entry=0x4898c0 <CryptoPP::NullAllocator<unsigned int>::deallocate(void*, unsigned long)::__PRETTY_FUNCTION__> "void CryptoPP::NullAllocator<T>::deallocate(void*, CryptoPP::NullAllocator<T>::size_type) [with T = unsigned int; CryptoPP::NullAllocator<T>::size_type = long unsigned int]")
    at assert.c:92
#3  0x00007ffff5a940f2 in __GI___assert_fail (assertion=0x489410 "false", 
    file=0x489498 "/usr/include/crypto++/secblock.h", line=151, 
    function=0x4898c0 <CryptoPP::NullAllocator<unsigned int>::deallocate(void*, unsigned long)::__PRETTY_FUNCTION__> "void CryptoPP::NullAllocator<T>::deallocate(void*, CryptoPP::NullAllocator<T>::size_type) [with T = unsigned int; CryptoPP::NullAllocator<T>::size_type = long unsigned int]") at assert.c:101
#4  0x000000000041a660 in CryptoPP::NullAllocator<unsigned int>::deallocate(void*, unsigned long) [clone .isra.35] ()
#5  0x00000000004453ee in Crypter::encrypt(SecureByteArray const&, SecureByteArray const&, QByteArray const&, CryptoPP::BlockPaddingSchemeDef::BlockPaddingSchem---Type <return> to continue, or q <return> to quit---
e) ()
#6  0x00000000004461f7 in Crypter::encode(SecureByteArray const&, SecureByteArray const&, QByteArray const&, SecureByteArray const&, QByteArray const&, bool)
    ()
#7  0x0000000000424e05 in MainWindow::saveAllDomainDataToSettings() ()
#8  0x0000000000425478 in MainWindow::saveCurrentDomainSettings() ()
#9  0x0000000000443616 in MainWindow::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00007ffff696f9c9 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff7344727 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff734490e in QAbstractButton::mousePressEvent(QMouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff728c89f in QWidget::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7248b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff724e8eb in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff693ec2b in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff724d3da in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEv---Type <return> to continue, or q <return> to quit---
ent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff72a4cc0 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff72a6e33 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff7248b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff724e000 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff693ec2b in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6c8bf82 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#24 0x00007ffff6c8db45 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff6c7234f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007fffef474590 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
---Type <return> to continue, or q <return> to quit---
#27 0x00007ffff5330c3d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff5330f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff5330fcc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6997c57 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff693c3e2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff694402c in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x000000000041a80e in main ()
```

This patch has been applied to link against the system crypro lib:
http://sprunge.us/gicd

**Comment by 607011** [comment]
Qt-SESAM is not supposed to work with anything else than the crypto++ lib that is included in the repository. So I won't consider your issue a bug ;-)
